services:

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: ${SAIL_SERVICE_PGADMIN}
        extra_hosts:
            - host.docker.internal:host-gateway
            - gateway.docker.internal:host-gateway
        ports:
            - '${PGADMIN_FORWARD_PORT}:80'
        environment:
            PGADMIN_DEFAULT_EMAIL: 'db@admin.org'
            PGADMIN_DEFAULT_PASSWORD: 'masterkey'
        volumes:
            - ../../data/pgadmin:/var/lib/pgadmin
        networks:
            - sail-services
