services:

    nginx:
        image: nginx:${NGINX_VERSION}
        container_name: ${SAIL_SERVICE_NGINX}
        extra_hosts:
            - host.docker.internal:host-gateway
            - gateway.docker.internal:host-gateway
        ports:
            - ${NGINX_PORT}:80
            - ${NGINX_PORT_HTTPS}:443
        environment:
            SAIL_ENV: ${SAIL_ENV}
            SERVER_ENVIRONMENT: ${SERVER_ENVIRONMENT}
        volumes:
            - ../../data/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - sail-services

networks:
    sail-services:
        driver: bridge
        name: ${COMPOSE_PROJECT_NAME}
